version: '2'
services:
    movieserviceexample-app:
        image: movieserviceexample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://movieserviceexample-postgresql:5432/MovieServiceExample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=movieserviceexample-elasticsearch:9300
        ports:
            - 8080:8080
    movieserviceexample-postgresql:
        extends:
            file: postgresql.yml
            service: movieserviceexample-postgresql
    movieserviceexample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: movieserviceexample-elasticsearch
